export const myProjects = [
  {
    title: "tempelet 1",
    description: "simple tempelate with Html & css with Elzero web school",
    category: ["css"],
    img: "https://i.ytimg.com/vi/uuBpOrrgY8w/maxresdefault.jpg",
    demo: "https://github.com/ehabyousef/tempelate-1",
    repo: "https://ehabyousef.github.io/tempelate-1/",
  },
  {
    title: "tempelet 2",
    description:
      "advanced tempelate with Html & css with Elzero web school using new techniques",
    category: ["css"],
    img: "https://i.ytimg.com/vi/uuBpOrrgY8w/maxresdefault.jpg",
    demo: "https://ehabyousef.github.io/html-css-series-project",
    repo: "https://ehabyousef.github.io/html-css-series-project/series.html",
  },
  {
    title: "tempelet 3",
    description:
      "more advanced tempelate with Html & css with Elzero web school using advanced techniques",
    category: ["css"],
    img: "https://i.ytimg.com/vi/uuBpOrrgY8w/maxresdefault.jpg",
    demo: "https://github.com/ehabyousef/tempelate-3",
    repo: "https://ehabyousef.github.io/tempelate-3//demo.html",
  },
  {
    title: "Drinks",
    description:
      "landing page for drinks with js & swipper js with a modern ui design ",
    category: ["js"],
    img: "https://mir-s3-cdn-cf.behance.net/project_modules/fs/6cfb8d59889433.5a32c074ee8c7.jpg",
    demo: "https://github.com/ehabyousef/landing-drinks",
    repo: "https://ehabyousef.github.io/landing-drinks/indesx.html",
  },
  {
    title: "social media",
    description: "social media web build with api using bootstrap && js ",
    category: ["js"],
    img: "https://mir-s3-cdn-cf.behance.net/project_modules/fs/6cfb8d59889433.5a32c074ee8c7.jpg",
    demo: "https://github.com/ehabyousef/socialmedia",
    repo: "https://timely-starlight-fb954f.netlify.app/",
  },
  {
    title: "College Web",
    description:
      "College Website builded for college task with team work using bootstrap && js && agile",
    category: ["js", "team"],
    img: "https://mir-s3-cdn-cf.behance.net/project_modules/fs/6cfb8d59889433.5a32c074ee8c7.jpg",
    demo: "https://github.com/ehabyousef/College-wepsite",
    repo: "https://ehabyousef.github.io/College-wepsite/",
  },
  {
    title: "games",
    description: "some simple games using js",
    category: ["js"],
    img: "https://mir-s3-cdn-cf.behance.net/project_modules/fs/6cfb8d59889433.5a32c074ee8c7.jpg",
    demo: "https://github.com/ehabyousef/x-o-Game",
    repo: "https://ehabyousef.github.io/x-o-Game/ddsdf",
  },
  {
    title: "portfolio ",
    description: "simple portfolio builded with html, css and javaScript",
    category: ["js"],
    img: "https://mir-s3-cdn-cf.behance.net/project_modules/fs/6cfb8d59889433.5a32c074ee8c7.jpg",
    demo: "https://github.com/ehabyousef/First-portfolio",
    repo: "https://ehabyousef.github.io/First-portfolio/",
  },
  {
    title: "my blog",
    description:
      "simple blog builded with html, css and javaScript for college task",
    category: ["js"],
    img: "https://mir-s3-cdn-cf.behance.net/project_modules/fs/6cfb8d59889433.5a32c074ee8c7.jpg",
    demo: "https://github.com/ehabyousef/my-blog",
    repo: "https://ehabyousef.github.io/my-blog/My%20blog.html",
  },
  {
    title: "crud ",
    description: "simple crud system  builded with react using hooks and api",
    category: ["React"],
    img: "https://2.bp.blogspot.com/-NggPwFgxT-s/WqeTskSLsUI/AAAAAAAAA58/Sknhc4Ya3nYFLlm56OgPtDNViov-ViOPACLcBGAs/s1600/1*weUJDeO1uAcuDj3NHT_6Bw.png",
    demo: "dsaaaaadsadsd",
    repo: "dsaddddsddsdf",
  },
  {
    title: "Mini Restaurant ",
    description: "simple web app builded with react using hooks",
    category: ["React"],
    img: "https://2.bp.blogspot.com/-NggPwFgxT-s/WqeTskSLsUI/AAAAAAAAA58/Sknhc4Ya3nYFLlm56OgPtDNViov-ViOPACLcBGAs/s1600/1*weUJDeO1uAcuDj3NHT_6Bw.png",
    demo: "https://github.com/ehabyousef/minirestaurant",
    repo: "/",
  },
  {
    title: "Food App",
    description:
      "simple crud system  builded with react using hooks and api worked with team for final training project",
    category: ["React", "team"],
    img: "https://2.bp.blogspot.com/-NggPwFgxT-s/WqeTskSLsUI/AAAAAAAAA58/Sknhc4Ya3nYFLlm56OgPtDNViov-ViOPACLcBGAs/s1600/1*weUJDeO1uAcuDj3NHT_6Bw.png",
    demo: "https://github.com/ehabyousef/f3g",
    repo: "dsaddddsddsdf",
  },
  {
    title: "Prayer Guide",
    description: "simple web app builded with react using hooks and api",
    category: ["React"],
    img: "https://2.bp.blogspot.com/-NggPwFgxT-s/WqeTskSLsUI/AAAAAAAAA58/Sknhc4Ya3nYFLlm56OgPtDNViov-ViOPACLcBGAs/s1600/1*weUJDeO1uAcuDj3NHT_6Bw.png",
    demo: "https://github.com/ehabyousef/prayer-guide",
    repo: "https://silly-squirrel-b16c62.netlify.app/",
  },
  {
    title: "shopping Cart",
    description: "simple shopping Cart builded with react using hooks and api ",
    category: ["React"],
    img: "https://2.bp.blogspot.com/-NggPwFgxT-s/WqeTskSLsUI/AAAAAAAAA58/Sknhc4Ya3nYFLlm56OgPtDNViov-ViOPACLcBGAs/s1600/1*weUJDeO1uAcuDj3NHT_6Bw.png",
    demo: "dsaaaaadsadsd",
    repo: "dsaddddsddsdf",
  },
  {
    title: "university web",
    description:
      "university web builded with react worked with team using agile",
    category: ["React", "team"],
    img: "https://2.bp.blogspot.com/-NggPwFgxT-s/WqeTskSLsUI/AAAAAAAAA58/Sknhc4Ya3nYFLlm56OgPtDNViov-ViOPACLcBGAs/s1600/1*weUJDeO1uAcuDj3NHT_6Bw.png",
    demo: "https://github.com/Gehad555/University_Services",
    repo: "dsaddddsddsdf",
  },
];
